apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }} #pv-local-ten
  labels:
    name: {{ .Values.pv.labels.name }} #storage
spec:
  capacity:
    storage: {{ .Values.pv.spec.storage }} #1Gi
  accessModes:
  - {{ .Values.pv.accessModes }} #ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.pv.storageClassName }} #local-storage
  local:
    path: {{ .Values.pv.local.path }} #/root/storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.pv.node }} #aks-agentpool-69194872-vmss000000