apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome!</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>Welcome to my world!</h1>
    <p>If you see this page, I'm Ten nice to meet you.</p>

    <p><em>Thank you for visit me LOL.</em></p>
    </body>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: hello-cm
  namespace: ten-fe
