apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hpa
    developer: ten
  name: hpa-backend
  namespace: ten-be
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
