apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hpa
    developer: ten
  name: hpa-frontend
  namespace: ten-fe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75
