bens: ten-be
fens: ten-fe

pv:
  name: pv-local-ten
  labels:
    name: storage
  spec:
    storage: 1Gi
  accessModes: ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /root/storage
  node: aks-agentpool-69194872-vmss000000

pvc:
  name: pvc-local-ten
  storageClassName: local-storage
  storage: 1Gi

secret:
  name: hello-secret
  namespace: ten-fe

configmap:
  name: hello-cm

Deployment:
  be:
    name: backend
    replicas: 2
    labels:
      app: hello
      tier: backend
      track: stable
    containers:
      name: hello
      image: tensjx/ten:be1.0.1
    ports:
      name: http
      containerPort: 3000
  fe:
    name: frontend
    replicas: 1
    labels:
      app: hello
      tier: frontend
      track: stable
    containers:
      name: nginx
      image: tensjx/ten:fe1.0.1
    volumeMounts:
      name: hello-v
      mountPath: /usr/share/nginx/html
    volumes:
      name: hello-v
    configMap:
      name: hello-cm

  limits:
    memory: "512Mi"
    cpu: "300m"
  requests:
    memory: "256Mi"
    cpu: "200m"

Service:
  be:
    name: hello
    selector:
      app: hello
      tier: backend
    ports:
      protocol: TCP
      port: 80
      targetPort: 3000
  fe:
    name: frontend
    selector:
      app: hello
      tier: frontend
    ports:
      protocol: "TCP"
      port: 80
      targetPort: 80

hpa:
  be:
    labels:
      app: hpa
      developer: ten
    name: hpa-backend
    spec:
      name: backend
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 75
  fe:
    labels:
      app: hpa
      developer: ten
    name: hpa-frontend
    spec:
      name: frontend
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 75


