apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ .Values.hpa.labels.app }} #hpa
    developer: {{ .Values.hpa.labels.developer }} #ten
  name: {{ .Values.hpa.name }} #hpa-frontend
  namespace: {{ .Release.namespace }} #ten-fe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.hpa.spec.name }} #frontend
  minReplicas: {{ .Values.hpa.spec.minReplicas }} #1
  maxReplicas: {{ .Values.hpa.spec.maxReplicas }} #2
  targetCPUUtilizationPercentage: {{ .Values.hpa.spec.targetCPUUtilizationPercentage }} #75