name: job-build
run-name: ${{ github.actor }} is learning GitHub Actions build job
on: [push]
jobs:
  job-build:
    runs-on: self-hosted
    steps:
      - name: check server-info
        run: lsb_release -a
      - name: git clone
        run: git clone https://github.com/Tensj/k8s.git -b minikube
      - name: helm install mychart-be
        run: |
          cd k8s/k8s-project/helm
          ls -lrt

          helm upgrade --install mychart-be -f k8s/k8s-project/helm/mychart-be/values.yaml mychart-be -n ten-be
      - name: helm install mychart-fe
        run: |
          cd k8s/k8s-project/helm
          ls -lrt

          helm upgrade --install mychart-fe -f k8s/k8s-project/helm/mychart-be/values.yaml mychart-fe -n ten-fe