name: undininable-ture
on:
  push:
    branches:
      - main
env:
  WORDING: "Ten"
  
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: check github environment
        run: hostname

      - name: build application
        run: echo "build for ${{ env.WORDING }}"
  deploy: 
    runs-on: ten
    steps:
      - name: check github environment
        run: hostname